# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    encoders:
        Web\AppBundle\Entity\User:
            algorithm: sha1
            encode_as_base64: false
            iterations: 1
    providers:
       users_provider:
           id: funglobe_user_provider
    role_hierarchy:
        ROLE_USER:        [ROLE_USER]
        ROLE_MODERATOR:   [ROLE_USER]
        ROLE_ADMIN:       [ROLE_MODERATOR]
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

    access_control:
        - { path: ^/[^/]+/admin, roles: ROLE_SUPER_ADMIN }
        - { path: ^/[^/]+/, roles: ROLE_USER }
        - { path: ^/profile, role: IS_AUTHENTICATED_FULLY }
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, roles: IS_AUTHENTICATED_ANONYMOUSLY }