# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    encoders:
        Web\AppBundle\Entity\User:
            algorithm: sha1
            encode_as_base64: false
            iterations: 1
        role_hierarchy:
            ROLE_USER:        [ROLE_USER]
            ROLE_MODERATOR:   [ROLE_USER]
            ROLE_ADMIN:       [ROLE_MODERATOR]
            ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]
        providers:
           users_provider:
               id: funglobe_user_provider

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        user:
            pattern: ^(fr|en)/profile
            security: true
        admin:
            pattern: ^(fr|en)/admin
            security: true
    access_control:
        - { path: ^/profile, roles: ROLE_USER }
        - { path: ^/admin, roles: ROLE_MODERATOR }