services:
    tootree_user_provider:
        class: Web\ApiBundle\Entity\User
        factory_service: doctrine.orm.entity_manager
        factory_method: getRepository
        arguments: [Web\ApiBundle\Entity\User]